In [2]:
import numpy as np
import time

# 1. Vector

## 1.1. Vector creation

In [9]:
a = np.zeros(4)
print(f"np.zeros(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4, ))
print(f"np.zeros((4, )): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.arange(4.)
print(f"np.arrange(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5, 4, 3, 2])
print(f"np.array([5, 4, 3, 2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5., 4, 3, 2])
print(f"np.array([5., 4, 3, 2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros((4, )): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.17145382 0.1201071  0.03390324 0.65760685], a shape = (4,), a data type = float64
np.arrange(4): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.64776191 0.69109551 0.24826506 0.51262914], a shape = (4,), a data type = float64
np.array([5, 4, 3, 2]): a = [5 4 3 2], a shape = (4,), a data type = int64
np.array([5., 4, 3, 2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


## 1.2. Operations on vector

### 1.2.1. Indexing

In [10]:
a = np.arange(10)
print(f"np.arrange(10): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, accessing an element returns a scalar")
print(f"a[-1] = {a[-1]}")

try:
    c = a[10]
except Exception as e:
    print(e)

np.arrange(10): a = [0 1 2 3 4 5 6 7 8 9], a shape = (10,), a data type = int64
a[2].shape: (), a[2] = 2, accessing an element returns a scalar
a[-1] = 9
index 10 is out of bounds for axis 0 with size 10


### 1.2.2. Slicing

In [11]:
a = np.arange(10)
print(f"a = {a}")

c = a[2:7:1]
print(f"a[2:7:1] = {c}")

c = a[2:7:2]
print(f"a[2:7:2] = {c}")

c = a[3:]
print(f"a[3:] = {c}")

c = a[:3]
print(f"a[:3] = {c}")

c = a[:]
print(f"a[:] = {c}")

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


### 1.2.3. Single vector operations

In [12]:
a = np.array([1, 2, 3, 4])
print(f"a = {a}")

b = -a
print(f"-a = {b}")

b = np.sum(a)
print(f"np.sum(a) = {b}")

b = np.mean(a)
print(f"np.mean(a) = {b}")

b = a**2
print(f"a**2 = {b}")

a = [1 2 3 4]
-a = [-1 -2 -3 -4]
np.sum(a) = 10
np.mean(a) = 2.5
a**2 = [ 1  4  9 16]


### 1.2.4. Vector element-wise operations

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 2, -5, 7])
print(f"Binary operations work element wise: {a + b}")

c = np.array([1, 0])
try:
    d = a + c 
except Exception as e:
    print(e)

Binary operations work element wise: [ 0  4 -2 11]
operands could not be broadcast together with shapes (4,) (2,) 


### 1.2.5. Scalar Vector Operations

In [15]:
a = np.array([1, 2, 3, 4])
b = 5 * a
print(f"5 * a = {b}")

5 * a = [ 5 10 15 20]


### 1.2.6. Vector dot product

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [18]:
def my_dot(a, b): 
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


### 1.2.7. Vector vs for loop

In [20]:
np.random.seed(1)
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(f"np.dot(a, b) = {c:.4f}")
print(f"Vectorized version duration: {1000*(toc - tic):.4f}ms")


tic = time.time()
c = my_dot(a, b)
toc = time.time()
print(f"my_dot(a, b) = {c:.4f}")
print(f"Loop version duration: {1000*(toc - tic):.4f}ms")

del(a)
del(b)

np.dot(a, b) = 249825.0234
Vectorized version duration: 0.8843ms
my_dot(a, b) = 249825.0234
Loop version duration: 420.0335ms


# 2. Matrix

## 2.1. Matrix creation

In [21]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.03762516]]


## 2.2. Matrix operation

### 2.2.1. Indexing

In [22]:
a = np.arange(6).reshape(-1, 2)   # = np.arange(6).reshape(3, 2)
print(f"a.shape: {a.shape}, \na= \n{a}")

print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= 
[[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


### 2.2.2. Slicing

In [28]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

print("\na[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

print("\na[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

print("\na[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("\na[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("\na[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array

a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)

a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array

a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
